"use client";

import { useMemo, useState } from "react";

type Category = "Company" | "Games" | "Anime" | "Locales";

type Milestone = {
  year: string;
  date: string;
  category: Category;
  title: string;
  text: string;
  source: string;
  sourceLabel: string;
  localeHref?: string;
  localeLabel?: string;
  image?: { src: string; alt: string; label: string };
};

const filters: Array<"All" | Category> = ["All", "Company", "Games", "Anime", "Locales"];

const milestones: Milestone[] = [
  { year: "1996", date: "27 FEB", category: "Games", title: "The source vocabulary enters play", text: "Pocket Monsters Red and Green launch in Japan. The creatures, places, mechanics, and Japanese wordplay established here become the source material every later localization must interpret.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history", localeHref: "/locales/japan", localeLabel: "Japan chapter", image: { src: "/exhibits/red-green.jpg", alt: "Japanese Pokémon Red and Green Game Boy boxes", label: "Source games · Japan · 1996" } },
  { year: "1997", date: "01 APR", category: "Anime", title: "Pokémon becomes a weekly television language", text: "The original animated series begins on TV Tokyo. Animation gives names voices, repeated pronunciation, character relationships, and a format that will often reach a locale before translated games do.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history", localeHref: "/locales/japan", localeLabel: "Japan chapter", image: { src: "/exhibits/anime-original.jpg", alt: "Artwork for the original Pokémon animated series", label: "Original television series · 1997" } },
  { year: "1998", date: "23 APR", category: "Company", title: "A company is built to manage Pokémon", text: "Pokémon Center Co., Ltd.—the predecessor of The Pokémon Company—is established. Globalization will require more than translated products: it will require long-term brand stewardship across games, animation, licensing, retail, and regional partners.", source: "https://corporate.pokemon.co.jp/en/aboutus/company", sourceLabel: "Official company profile" },
  { year: "1998", date: "07 SEP", category: "Anime", title: "The English adaptation begins in the United States", text: "The first episode enters U.S. syndication across 111 stations. The adaptation introduces an English cast of names and phrases that will influence later dubs made from the English television version.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history", localeHref: "/locales/united-states", localeLabel: "United States chapter" },
  { year: "1998", date: "28 SEP", category: "Games", title: "Red and Blue establish the English reference edition", text: "The U.S. games arrive three weeks after the television debut. Their localized species names become an international reference layer—sometimes translated again, sometimes transcribed, and sometimes retained unchanged.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history", localeHref: "/locales/united-states", localeLabel: "United States chapter", image: { src: "/exhibits/red-blue.jpg", alt: "Pokémon Red and Blue Game Boy boxes", label: "English-language games · 1998" } },
  { year: "1998", date: "16 NOV", category: "Locales", title: "A Cantonese Pokémon vocabulary reaches Hong Kong television", text: "Hong Kong’s first documented television broadcast begins a distinct Cantonese naming tradition. It later becomes central to the debate over unified Chinese written names.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_Hong_Kong", sourceLabel: "Hong Kong history index", localeHref: "/locales/hong-kong", localeLabel: "Hong Kong chapter" },
  { year: "1998", date: "28 NOV", category: "Locales", title: "Taiwan begins its own Mandarin broadcast history", text: "The animated series begins on CTV. Taiwan shares Traditional Chinese script with Hong Kong in many products, but its Mandarin readings, broadcasters, distributors, and terminology history form a separate locale record.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_Taiwan", sourceLabel: "Taiwan history index", localeHref: "/locales/taiwan", localeLabel: "Taiwan chapter" },
  { year: "1999", date: "26 APR", category: "Anime", title: "Latin America develops a regional Spanish voice", text: "The Latin American Spanish adaptation begins. Its casting, register, titles, and terminology build a regional television tradition decades before a separate Latin American Spanish option appears in a core game.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_Latin_America", sourceLabel: "Latin America history index", localeHref: "/locales/latin-america", localeLabel: "Latin America chapter" },
  { year: "1999", date: "10 MAY", category: "Anime", title: "Brazilian Portuguese becomes a mass-media Pokémon language", text: "The anime premieres on RecordTV. Brazil’s dubbing tradition gives the locale an established Pokémon vocabulary long before Brazilian Portuguese is confirmed for a main-series game.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_Brazil", sourceLabel: "Brazil history index", localeHref: "/locales/brazil", localeLabel: "Brazil chapter", image: { src: "/exhibits/brazil-horizons.jpg", alt: "Brazilian Portuguese Pokémon Horizons poster", label: "A continuing Brazilian dub tradition" } },
  { year: "1999", date: "01 OCT", category: "Anime", title: "Pokémon enters Philippine television in English", text: "GMA begins the English broadcast that precedes a later Filipino dub. The two traditions share international species names while differing in voice, dialogue, and audience memory.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_the_Philippines", sourceLabel: "Philippines history index", localeHref: "/locales/philippines", localeLabel: "Philippines chapter", image: { src: "/exhibits/philippines-portal.png", alt: "Official Pokémon Philippines portal artwork", label: "Official regional portal" } },
  { year: "1999", date: "02 OCT", category: "Anime", title: "European Portuguese Pokémon begins on SIC", text: "Portugal’s dub localizes dialogue, music, titles, and terminology around species names that generally retain their international spelling.", source: "https://bulbapedia.bulbagarden.net/wiki/Pokemon_in_Portugal", sourceLabel: "Portugal history index", localeHref: "/locales/portugal", localeLabel: "Portugal chapter", image: { src: "/exhibits/portugal-horizons-logo.png", alt: "European Portuguese Pokémon Horizontes logo", label: "Portugal title artifact" } },
  { year: "1999", date: "05–08 OCT", category: "Games", title: "The first European localization set arrives", text: "German, Italian, Spanish, and French editions of Red and Blue establish four long-running game-text traditions. Their approaches range from extensive species-name adaptation to retaining the English name set inside otherwise localized games.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Red_and_Blue_Versions", sourceLabel: "Red and Blue release record", localeHref: "/#locales", localeLabel: "Compare European locales", image: { src: "/exhibits/french-blue.jpg", alt: "French Pokémon Version Bleue Game Boy box", label: "One artifact from the 1999 European set" } },
  { year: "2000", date: "OCT", category: "Company", title: "The Pokémon Company takes its present name", text: "Pokémon Center Co., Ltd. becomes The Pokémon Company and expands its remit to overall brand management. The change reflects a franchise now operating across far more than retail stores or one product line.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history" },
  { year: "2000", date: "EARLY", category: "Anime", title: "Hebrew Pokémon begins in Israel", text: "The Israeli Children Channel starts a Hebrew dub that writes retained English species identities from right to left. Its later hiatus and 2016 return become part of the locale’s chronology.", source: "https://bulbapedia.bulbagarden.net/wiki/Pokemon_in_Israel", sourceLabel: "Israel history index", localeHref: "/locales/israel", localeLabel: "Israel chapter", image: { src: "/exhibits/hebrew-pokemon-logo.png", alt: "Official Hebrew Pokémon title logo", label: "Hebrew title artifact" } },
  { year: "2000", date: "DAY UNRESOLVED", category: "Anime", title: "A pan-Arabic dub reaches MBC", text: "A Syrian-produced Arabic edition brings Pokémon to a cross-border satellite audience. Later productions and platforms create a multi-studio regional archive rather than one national version.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_the_Arab_world", sourceLabel: "Arab world history index", localeHref: "/locales/arab-world", localeLabel: "Arab world chapter", image: { src: "/exhibits/arabic-pokemon-logo.png", alt: "Official Arabic Pokémon title logo", label: "Arabic title artifact" } },
  { year: "2000", date: "25 NOV", category: "Anime", title: "Malaysia’s multilingual Pokémon screen history begins", text: "The first documented broadcast precedes Malay dubs made from different source editions: Diamond and Pearl from Japanese, then Black & White from English.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_Malaysia", sourceLabel: "Malaysia history index", localeHref: "/locales/malaysia", localeLabel: "Malaysia chapter", image: { src: "/exhibits/malaysia-portal.png", alt: "Official Pokémon Malaysia portal artwork", label: "Official regional portal" } },
  { year: "2001", date: "FEB", category: "Company", title: "Pokémon USA creates permanent international infrastructure", text: "Pokémon USA, Inc.—now part of The Pokémon Company International—is established. English-language and international management become an enduring organization rather than a one-release campaign.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history", localeHref: "/locales/united-states", localeLabel: "United States chapter" },
  { year: "2001", date: "03 MAR", category: "Anime", title: "Indonesia receives its first official Pokémon dub", text: "Episode one premieres on SCTV in Indonesian. The arrival begins a locale history later expanded through official YouTube publishing, mobile-game distribution, the Indonesian TCG, events, and a dedicated Pokémon web portal.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_Indonesia", sourceLabel: "Indonesia media history", localeHref: "/locales/indonesia", localeLabel: "Indonesia chapter", image: { src: "/exhibits/indonesia-pokemon-go.png", alt: "Pokémon GO promotional art on the official Indonesian Pokémon apps portal", label: "A later mobile layer in the Indonesian locale" } },
  { year: "2002", date: "24 APR", category: "Games", title: "Korean becomes a playable core-game language", text: "Localized Gold and Silver editions arrive in South Korea. They form the first official Korean main-series game release, after the anime had already introduced Pokémon to television audiences.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_South_Korea", sourceLabel: "South Korea release history", localeHref: "/locales/south-korea", localeLabel: "South Korea chapter", image: { src: "/exhibits/gold-silver-korea.jpg", alt: "Korean Pokémon Gold and Silver Game Boy Color boxes", label: "First Korean core games · 2002" } },
  { year: "2003", date: "MAR", category: "Company", title: "A London office anchors European operations", text: "A representative office—now part of The Pokémon Company International’s footprint—is established in London, marking a durable European organizational presence.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history" },
  { year: "2003", date: "12 MAY", category: "Anime", title: "Hindi begins Pokémon’s multilingual Indian broadcast story", text: "The Hindi television debut becomes the first major language marker in the India chapters. Later Tamil and Telugu dubs, regional channels, and digital archives make India a deliberately multi-page locale in this exhibition.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_South_Asia", sourceLabel: "South Asia broadcast index", localeHref: "/locales/india", localeLabel: "India overview", image: { src: "/exhibits/india-horizons.jpg", alt: "Pokémon Horizons India poster", label: "India’s multilingual anime archive" } },
  { year: "2006", date: "AUG", category: "Company", title: "Pokémon Korea is established", text: "A dedicated regional company creates permanent infrastructure for games, animation, cards, events, and local brand management in South Korea.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history", localeHref: "/locales/south-korea", localeLabel: "South Korea chapter" },
  { year: "2013", date: "12 OCT", category: "Games", title: "X and Y launch worldwide at the same time", text: "For the first time, a main-series Pokémon generation receives a simultaneous worldwide release. Localization moves from a staggered regional afterlife toward one coordinated launch window.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history", image: { src: "/exhibits/x-box.jpg", alt: "Pokémon X game box", label: "First simultaneous worldwide core launch" } },
  { year: "2016", date: "31 MAY", category: "Locales", title: "Hong Kong fans protest Pikachu’s unified written name", text: "The replacement of the established Cantonese 比卡超 with 皮卡丘 becomes a public controversy. The reaction demonstrates why script labels alone cannot describe what listeners hear when the same characters are read in different spoken varieties.", source: "https://kotaku.com/hong-kong-pokemon-fans-protest-pikachus-name-change-1779471301", sourceLabel: "Contemporary protest report", localeHref: "/locales/hong-kong", localeLabel: "Hong Kong chapter" },
  { year: "2016", date: "18 NOV", category: "Games", title: "Chinese becomes selectable in the core series", text: "Sun and Moon add Simplified and Traditional Chinese. The milestone expands the game’s language menu while also exposing a difficult truth: one coordinated written standard does not erase Hong Kong, Taiwan, and mainland China’s different spoken and media histories.", source: "https://bulbapedia.bulbagarden.net/wiki/List_of_Chinese_Pok%C3%A9mon_names", sourceLabel: "Chinese-name history index", localeHref: "/locales/taiwan", localeLabel: "Begin with the Taiwan chapter", image: { src: "/exhibits/chinese-sun-moon-traditional.jpg", alt: "Pokémon Sun and Moon boxes with Traditional Chinese titles", label: "Traditional Chinese game artwork · 2016" } },
  { year: "2019", date: "17 MAY", category: "Anime", title: "Vietnam’s original-series archive starts online", text: "POPS Kids begins publishing a Vietnamese dub of the original series from episode one. Dated digital uploads turn an earlier broadcast history into a searchable public record.", source: "https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_in_Vietnam", sourceLabel: "Vietnam media history", localeHref: "/locales/vietnam", localeLabel: "Vietnam chapter", image: { src: "/exhibits/vietnam-horizons.jpg", alt: "Vietnamese Pokémon Horizons poster", label: "Vietnamese-language animation" } },
  { year: "2022", date: "DEC", category: "Company", title: "Pokémon Taiwan Co., Ltd. is established", text: "The corporate timeline records a dedicated Taiwan company. It arrives decades after the locale’s first television broadcasts, showing why corporate entry and cultural arrival must remain separate dates.", source: "https://corporate.pokemon.co.jp/en/aboutus/history", sourceLabel: "The Pokémon Company history", localeHref: "/locales/taiwan", localeLabel: "Taiwan chapter" },
  { year: "2024", date: "19 JUL", category: "Anime", title: "India’s official digital archive expands", text: "Pokémon Horizons becomes available on YouTube and an official South Asia English channel launches. Alongside dedicated Hindi, Tamil, and Telugu publishing, online distribution makes language-specific titles and upload dates visible evidence.", source: "https://in.portal-pokemon.com/topics/?c=tv-film", sourceLabel: "Official Pokémon India topics", localeHref: "/locales/india", localeLabel: "India overview", image: { src: "/exhibits/india-horizons.jpg", alt: "Pokémon Horizons India poster", label: "Official India digital distribution" } },
  { year: "2025", date: "25 SEP", category: "Locales", title: "Pokémon unifies species names across India", text: "The official India site announces that Hindi names will align with Tamil, Telugu, and Bengali around English-based species names. The policy preserves multiple language performances while standardizing the cross-language name layer.", source: "https://in.portal-pokemon.com/topics/pokemon_names_unified_across_india/", sourceLabel: "Official India naming policy", localeHref: "/locales/hindi-india", localeLabel: "Hindi chapter" },
  { year: "2025", date: "16 OCT", category: "Games", title: "Latin American Spanish enters a core game", text: "Pokémon Legends: Z-A supplies a separate Latin American Spanish option. The game milestone follows roughly twenty-six years of regional Spanish-language animation rather than beginning the locale’s history.", source: "https://www.linkedin.com/posts/tomascortijo_pok%C3%A9mon-presents-2272025-activity-7301045323886415872-GPT1", sourceLabel: "Regional director’s announcement", localeHref: "/locales/latin-america", localeLabel: "Latin America chapter", image: { src: "/exhibits/legends-za-latam.jpg", alt: "Latin American retail cover for Pokémon Legends Z-A", label: "First Latin American Spanish core-game edition" } },
  { year: "2026", date: "27 FEB", category: "Games", title: "Brazilian Portuguese is confirmed for the 2027 core games", text: "Pokémon Winds and Waves is announced with Brazilian Portuguese support. This is a confirmed future language milestone, not a claim that the game launched in 2026; the playable-language date belongs to its 2027 release.", source: "https://www.nintendo.com/pt-br/store/products/pokemon-waves-switch-2/", sourceLabel: "Official Nintendo Brazil listing", localeHref: "/locales/future", localeLabel: "Future evidence desk", image: { src: "/exhibits/winds-waves.jpg", alt: "Pokémon Winds and Waves announcement artwork", label: "Announced in 2026 · release expected 2027" } },
  { year: "2026", date: "25 MAY", category: "Locales", title: "Vietnam adopts the English species-name standard", text: "The official Vietnam site announces that future content and services will consistently use English species names. Earlier Japanese-rooted Vietnam-market spellings remain part of the historical record rather than disappearing from the exhibit.", source: "https://vn.portal-pokemon.com/topics/post-5775/", sourceLabel: "Official Vietnam naming notice", localeHref: "/locales/vietnam", localeLabel: "Vietnam chapter" },
  { year: "2027", date: "ANNOUNCED", category: "Games", title: "Brazilian Portuguese is scheduled to become playable", text: "Winds and Waves is the first announced main-series game with Brazilian Portuguese text. Exact release timing and species-name implementation remain future evidence questions until the product arrives.", source: "https://www.nintendo.com/pt-br/store/products/pokemon-waves-switch-2/", sourceLabel: "Official Nintendo Brazil listing", localeHref: "/locales/future", localeLabel: "Future evidence desk" },
];

export default function HistoryPage() {
  const [activeFilter, setActiveFilter] = useState<(typeof filters)[number]>("All");
  const visibleMilestones = useMemo(() => activeFilter === "All" ? milestones : milestones.filter((item) => item.category === activeFilter), [activeFilter]);

  return <main className="timeline-chapter" id="top">
    <nav className="nav timeline-chapter-nav" aria-label="History navigation">
      <a className="brand" href="/" aria-label="Pokélingua home"><span className="brand-mark" aria-hidden="true"><i /></span><span>Pokélingua</span></a>
      <div className="nav-links"><a href="/about">About the Exhibit</a><a href="/#locales">Locales</a><a href="/#pokemon-search">Pokémon search</a><a href="/name-routes">Name routes</a></div>
      <a className="nav-cta" href="/#locales">Explore locales <span>↗</span></a>
    </nav>

    <header className="timeline-chapter-hero">
      <div className="timeline-chapter-index"><span>Chronology chapter / 01</span><b>1996<br />—<br />2027</b><small>Documented past<br />announced future</small></div>
      <div className="timeline-chapter-intro"><span>Pokémon across borders and media</span><h1>One phenomenon.<br /><em>Many clocks.</em></h1><p>A game can launch after a television dub. A company can arrive decades after its audience. A standardized name can follow years of regional use. This history keeps those events in chronological conversation without pretending they are the same kind of milestone.</p><div><a className="primary-button" href="#chronology">Enter the chronology <span>↓</span></a><a className="text-link" href="/about">Read About the Exhibit <span>↗</span></a></div></div>
    </header>

    <section className="timeline-chapter-method">
      <div><span>Four evidence lenses</span><h2>Filter the history,<br />not the context.</h2></div>
      <div className="timeline-lens-grid">
        <article><b>Company</b><p>Organizations and offices that turned releases into permanent regional infrastructure.</p></article>
        <article><b>Games</b><p>Launches and the first moment a language became playable in the core series.</p></article>
        <article><b>Anime</b><p>Broadcast and digital-dub milestones that often created local vocabulary first.</p></article>
        <article><b>Locales</b><p>Naming policies, controversies, and territory-specific decisions that language labels hide.</p></article>
      </div>
    </section>

    <section className="timeline-chronology" id="chronology">
      <div className="timeline-chronology-head"><div><span>Exhibit record / sourced milestones</span><h2>The chronology</h2></div><p>This is a curated globalization timeline, not a list of every Pokémon release. Dates are precise where the public record supports precision; month-only and announced-future markers stay visibly qualified.</p></div>
      <div className="timeline-chapter-filters" role="group" aria-label="Filter chronology by evidence lens">
        {filters.map((filter) => <button key={filter} className={activeFilter === filter ? "active" : ""} onClick={() => setActiveFilter(filter)} aria-pressed={activeFilter === filter}>{filter}<span>{filter === "All" ? milestones.length : milestones.filter((item) => item.category === filter).length}</span></button>)}
      </div>
      <div className="timeline-chapter-list" aria-live="polite">
        {visibleMilestones.map((item, index) => <article className="timeline-chapter-event" key={`${item.year}-${item.date}-${item.title}`}>
          <aside><time>{item.year}</time><span>{item.date}</span><i aria-hidden="true" /></aside>
          <div className="timeline-event-copy"><span>{item.category} / record {String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.text}</p><div><a href={item.source} target="_blank" rel="noreferrer">Source · {item.sourceLabel} ↗</a>{item.localeHref && <a href={item.localeHref}>{item.localeLabel} →</a>}</div></div>
          {item.image && <figure><img src={item.image.src} alt={item.image.alt} loading="lazy" /><figcaption>{item.image.label}</figcaption></figure>}
        </article>)}
      </div>
      <div className="timeline-chapter-note"><span>How dates work</span><p>A corporate founding, first broadcast, product announcement, game launch, and naming-policy change answer different historical questions. Pokélingua records the event type beside the date and does not convert an announcement year into a release year.</p></div>
    </section>

    <footer className="timeline-footer"><a className="brand footer-brand" href="/"><span className="brand-mark" aria-hidden="true"><i /></span><span>Pokélingua</span></a><p>A living atlas of Pokémon localization.</p><a href="#top">Back to top ↑</a></footer>
  </main>;
}
